services:
  auth-db:
    container_name: auth-postgres
    image: postgres:16.8-alpine3.20
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
